### ISSUE TITLE
To many network calls hapen on scrolling

### ISSUE THREAD

**Issue by imkuldeepahlawat** [imkuldeepahlawat/Face-Prep-Assignment#1]
### First time load
![Face Prep Assignment — Mozilla Firefox 20-07-2023 00_08_56](https://github.com/imkuldeepahlawat/Face-Prep-Assignment/assets/84150035/ad3fb2c9-1e9e-4756-a5f7-76bd9e88c1df)

### First Scroll
![Face Prep Assignment — Mozilla Firefox 20-07-2023 00_09_47](https://github.com/imkuldeepahlawat/Face-Prep-Assignment/assets/84150035/fd4628ed-5738-45d1-a61d-0fbd83fdf33d)

**Comment by imkuldeepahlawat** [comment]
username:- foo
password:- bar
### don't try to hack the userAccount😉

**Comment by ThaungThanHan** [comment]
Hello @imkuldeepahlawat. I am on it.

**Comment by imkuldeepahlawat** [comment]
Gald to here,make a branch with your name when you fix it just make a pr @ThaungThanHan

**Comment by imkuldeepahlawat** [comment]
@ThaungThanHan  ThankYou Budddy, to fix this issue, ping me on @gmail.com with my Git username
